### ISSUE TITLE
Add To Shortlist is Bugged

### ISSUE THREAD

**Issue by arnaav11** [lakshya076/Cinematch#11]
Pressing Add to Shortlist adds the movie opened before the current movie in specific cases.

FIX THIS GARBAGE!!!!!!!

**Comment by lakshya076** [comment]
Hi Arnav,
Thanks for bringing this to my notice
I will look into it asap and will update you

**Comment by lakshya076** [comment]
Hi Arnav,
Can you please describe your issue in detail
Like in what cases does the bug occur and does it occur in random movies or display movies or both

**Comment by lakshya076** [comment]
Hi Arnav,
This issue has been resolved. It will be patched in the next public version

**Comment by lakshya076** [comment]
Check [release v0.2-beta.1](https://github.com/lakshya076/Cinematch/releases/tag/v0.2-beta.1) for bug fix

**Comment by arnaav11** [comment]
Hey, thank you for fixing the bug, it works great now!
